# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_SEC_P4NOTE_SWITCH) += sec_common.o
obj-$(CONFIG_SEC_P4NOTE_SWITCH) += px_switch.o

obj-$(CONFIG_SEC_P4NOTE_30_PIN_CON) += 30pin_con.o

obj-$(CONFIG_SEC_P4NOTE_CHARGING) += max17042_fuelgauge_px.o
obj-$(CONFIG_SEC_P4NOTE_CHARGING) += smb347_charger.o
obj-$(CONFIG_SEC_P4NOTE_CHARGING) += sec_battery_px.o

obj-$(CONFIG_SEC_P4NOTE_KEYBOARD) += sec_keyboard.o

obj-$(CONFIG_P4NOTE_IRQ_FUN) = irq_fun.o